In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("application_train.csv")

In [3]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round((df.isnull().sum()/len(df))*100,2)
})

missing = missing.sort_values(
    by="Percentage",
    ascending=False
)

missing.head(20)

                          Missing Values  Percentage
COMMONAREA_MEDI                   214865       69.87
COMMONAREA_AVG                    214865       69.87
COMMONAREA_MODE                   214865       69.87
NONLIVINGAPARTMENTS_MODE          213514       69.43
NONLIVINGAPARTMENTS_AVG           213514       69.43
NONLIVINGAPARTMENTS_MEDI          213514       69.43
FONDKAPREMONT_MODE                210295       68.39
LIVINGAPARTMENTS_MODE             210199       68.35
LIVINGAPARTMENTS_AVG              210199       68.35
LIVINGAPARTMENTS_MEDI             210199       68.35
FLOORSMIN_AVG                     208642       67.85
FLOORSMIN_MODE                    208642       67.85
FLOORSMIN_MEDI                    208642       67.85
YEARS_BUILD_MEDI                  204488       66.50
YEARS_BUILD_MODE                  204488       66.50
YEARS_BUILD_AVG                   204488       66.50
OWN_CAR_AGE                       202929       65.99
LANDAREA_MEDI                     182590       59.38
LANDAREA_MODE                     182590       59.38
LANDAREA_AVG                      182590       59.38

In [4]:
duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

Duplicate Rows : 0

In [5]:
df.dtypes

SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
                               ...
AMT_REQ_CREDIT_BUREAU_DAY     float64
AMT_REQ_CREDIT_BUREAU_WEEK    float64
AMT_REQ_CREDIT_BUREAU_MON     float64
AMT_REQ_CREDIT_BUREAU_QRT     float64
AMT_REQ_CREDIT_BUREAU_YEAR    float64
Length: 122, dtype: object

In [6]:
df.memory_usage(deep=True)

Index                              132
SK_ID_CURR                     2460088
TARGET                         2460088
NAME_CONTRACT_TYPE            18289544
CODE_GENDER                   15375558
                                ...
AMT_REQ_CREDIT_BUREAU_DAY      2460088
AMT_REQ_CREDIT_BUREAU_WEEK     2460088
AMT_REQ_CREDIT_BUREAU_MON      2460088
AMT_REQ_CREDIT_BUREAU_QRT      2460088
AMT_REQ_CREDIT_BUREAU_YEAR     2460088
Length: 123, dtype: int64

In [7]:
missing_summary = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage (%)': round((df.isnull().sum() / len(df)) * 100, 2)
})

missing_summary = missing_summary.sort_values(
    by='Percentage (%)',
    ascending=False
)

missing_summary.head(20)

                          Missing Values  Percentage (%)
COMMONAREA_MEDI                   214865           69.87
COMMONAREA_AVG                    214865           69.87
COMMONAREA_MODE                   214865           69.87
NONLIVINGAPARTMENTS_MODE          213514           69.43
NONLIVINGAPARTMENTS_AVG           213514           69.43
NONLIVINGAPARTMENTS_MEDI          213514           69.43
FONDKAPREMONT_MODE                210295           68.39
LIVINGAPARTMENTS_MODE             210199           68.35
LIVINGAPARTMENTS_AVG              210199           68.35
LIVINGAPARTMENTS_MEDI             210199           68.35
FLOORSMIN_AVG                     208642           67.85
FLOORSMIN_MODE                    208642           67.85
FLOORSMIN_MEDI                    208642           67.85
YEARS_BUILD_MEDI                  204488           66.50
YEARS_BUILD_MODE                  204488           66.50
YEARS_BUILD_AVG                   204488           66.50
OWN_CAR_AGE                       202929           65.99
LANDAREA_MEDI                     182590           59.38
LANDAREA_MODE                     182590           59.38
LANDAREA_AVG                      182590           59.38

In [8]:
high_missing = missing_summary[
    missing_summary['Percentage (%)'] > 50
]

high_missing

                          Missing Values  Percentage (%)
COMMONAREA_MEDI                   214865           69.87
COMMONAREA_AVG                    214865           69.87
COMMONAREA_MODE                   214865           69.87
NONLIVINGAPARTMENTS_MODE          213514           69.43
NONLIVINGAPARTMENTS_AVG           213514           69.43
NONLIVINGAPARTMENTS_MEDI          213514           69.43
FONDKAPREMONT_MODE                210295           68.39
LIVINGAPARTMENTS_MODE             210199           68.35
LIVINGAPARTMENTS_AVG              210199           68.35
LIVINGAPARTMENTS_MEDI             210199           68.35
FLOORSMIN_AVG                     208642           67.85
FLOORSMIN_MODE                    208642           67.85
FLOORSMIN_MEDI                    208642           67.85
YEARS_BUILD_MEDI                  204488           66.50
YEARS_BUILD_MODE                  204488           66.50
YEARS_BUILD_AVG                   204488           66.50
OWN_CAR_AGE                       202929           65.99
LANDAREA_MEDI                     182590           59.38
LANDAREA_MODE                     182590           59.38
LANDAREA_AVG                      182590           59.38
BASEMENTAREA_MEDI                 179943           58.52
BASEMENTAREA_AVG                  179943           58.52
BASEMENTAREA_MODE                 179943           58.52
EXT_SOURCE_1                      173378           56.38
NONLIVINGAREA_MODE                169682           55.18
NONLIVINGAREA_AVG                 169682           55.18
NONLIVINGAREA_MEDI                169682           55.18
ELEVATORS_MEDI                    163891           53.30
ELEVATORS_AVG                     163891           53.30
ELEVATORS_MODE                    163891           53.30
WALLSMATERIAL_MODE                156341           50.84
APARTMENTS_MEDI                   156061           50.75
APARTMENTS_AVG                    156061           50.75
APARTMENTS_MODE                   156061           50.75
ENTRANCES_MEDI                    154828           50.35
ENTRANCES_AVG                     154828           50.35
ENTRANCES_MODE                    154828           50.35
LIVINGAREA_AVG                    154350           50.19
LIVINGAREA_MODE                   154350           50.19
LIVINGAREA_MEDI                   154350           50.19
HOUSETYPE_MODE                    154297           50.18

In [9]:
print("Columns with more than 50% missing values:",
      len(high_missing))

Columns with more than 50% missing values: 41

In [10]:
high_missing.index.tolist()

['COMMONAREA_MEDI',
 'COMMONAREA_AVG',
 'COMMONAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAPARTMENTS_MEDI',
 'FONDKAPREMONT_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAPARTMENTS_MEDI',
 'FLOORSMIN_AVG',
 'FLOORSMIN_MODE',
 'FLOORSMIN_MEDI',
 'YEARS_BUILD_MEDI',
 'YEARS_BUILD_MODE',
 'YEARS_BUILD_AVG',
 'OWN_CAR_AGE',
 'LANDAREA_MEDI',
 'LANDAREA_MODE',
 'LANDAREA_AVG',
 'BASEMENTAREA_MEDI',
 'BASEMENTAREA_AVG',
 'BASEMENTAREA_MODE',
 'EXT_SOURCE_1',
 'NONLIVINGAREA_MODE',
 'NONLIVINGAREA_AVG',
 'NONLIVINGAREA_MEDI',
 'ELEVATORS_MEDI',
 'ELEVATORS_AVG',
 'ELEVATORS_MODE',
 'WALLSMATERIAL_MODE',
 'APARTMENTS_MEDI',
 'APARTMENTS_AVG',
 'APARTMENTS_MODE',
 'ENTRANCES_MEDI',
 'ENTRANCES_AVG',
 'ENTRANCES_MODE',
 'LIVINGAREA_AVG',
 'LIVINGAREA_MODE',
 'LIVINGAREA_MEDI',
 'HOUSETYPE_MODE']

In [ ]:
## Missing Value Analysis
# This step identifies columns with a high percentage of missing values. 
# Columns are not removed immediately because, in financial datasets, missing values may carry business meaning rather than indicating poor data quality.

In [11]:
print(f"Columns with more than 50% missing values: {len(high_missing)}")

Columns with more than 50% missing values: 41